"""Landing page renderer — loads templates/landing.html via FileSystemLoader."""
from __future__ import annotations
from collections import defaultdict
import os
from pathlib import Path
import jinja2

from ..models import Section

_LANDING_DESCRIPTION = (
    "Portland State University Department of Computer Science: undergraduate, "
    "graduate, and student resources, plus an AI assistant trained on department content."
)


def _site_base_url() -> str:
    return os.getenv("SITE_BASE_URL", "https://web.cs.pdx.edu").rstrip("/")


def meta_description(text: str, max_len: int = 160) -> str:
    clean = " ".join(text.split())
    if len(clean) <= max_len:
        return clean
    truncated = clean[:max_len]
    last_space = truncated.rfind(" ")
    return (truncated[:last_space] if last_space > 0 else truncated) + "…"


_TEMPLATES_DIR = Path(__file__).parent.parent.parent / "templates"

CATEGORY_LABELS = {
    "about": "About",
    "undergraduate": "Undergraduate",
    "graduate": "Graduate",
    "resources": "Resources",
}

CATEGORY_ICONS = {
    "about": "🏛️",
    "undergraduate": "🎓",
    "graduate": "📚",
    "resources": "🛟",
}

CATEGORY_ORDER = [
    "about",
    "undergraduate",
    "graduate",
    "resources",
]


def build_nav_groups(
    sections: list[Section],
    exclude_ids: list[str] | None = None,
) -> list[tuple[str, list[Section]]]:
    """Group sections by category in canonical display order, omitting exclude_ids.

    Within a category, sections keep the order they arrive in — which is source
    order: the Google Doc's own tab order (the Docs API returns `tabs` top-to-bottom
    as they appear in the tab pane), then one entry per whole-doc, in `content.yaml`
    `docs[]` order. So the way to reorder a dropdown or a landing-page column is to
    drag the tab in the Doc; only order *within* a category matters, since sections
    are bucketed by category first. Sorting here instead (e.g. by title) would
    override that and take the control away from the doc author.
    """
    skip = set(exclude_ids or [])
    by_cat: dict[str, list[Section]] = defaultdict(list)
    for s in sections:
        if s.id not in skip:
            by_cat[s.category or "other"].append(s)
    ordered = [(c, by_cat[c]) for c in CATEGORY_ORDER if c in by_cat]
    extras = sorted(c for c in by_cat if c not in CATEGORY_ORDER)
    ordered += [(c, by_cat[c]) for c in extras]
    return ordered


def render_landing(
    sections: list[Section],
    out_path: str,
    base_href: str = "/",
    exclude_ids: list[str] | None = None,
) -> None:
    """Render the landing page from templates/landing.html.

    `exclude_ids` is a list of section ids to hide from the landing index.
    The corresponding HTML pages are still generated by render_sections()
    and remain reachable by URL; they're just omitted from the home page
    (and from the in-page nav / footer / quick links).
    """
    nav_groups = build_nav_groups(sections, exclude_ids)

    canonical_url = _site_base_url() + "/"
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(_TEMPLATES_DIR)))
    tpl = env.get_template("landing.html")
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(
        tpl.render(
            nav_groups=nav_groups,
            cat_labels=CATEGORY_LABELS,
            cat_icons=CATEGORY_ICONS,
            base_href=base_href,
            canonical_url=canonical_url,
            meta_description=_LANDING_DESCRIPTION,
        ),
        encoding="utf-8",
    )
