"""Landing page renderer — loads templates/landing.html via FileSystemLoader."""
from __future__ import annotations
from collections import defaultdict
from pathlib import Path
import jinja2

from ..models import Section


_TEMPLATES_DIR = Path(__file__).parent.parent.parent / "templates"

CATEGORY_LABELS = {
    "about": "About",
    "undergraduate": "Undergraduate",
    "graduate": "Graduate",
    "resources": "Resources",
}

CATEGORY_ICONS = {
    "about": "🏛️",
    "undergraduate": "🎓",
    "graduate": "📚",
    "resources": "🛟",
}

CATEGORY_ORDER = [
    "about",
    "undergraduate",
    "graduate",
    "resources",
]


def build_nav_groups(
    sections: list[Section],
    exclude_ids: list[str] | None = None,
) -> list[tuple[str, list[Section]]]:
    """Group sections by category in canonical display order, omitting exclude_ids."""
    skip = set(exclude_ids or [])
    by_cat: dict[str, list[Section]] = defaultdict(list)
    for s in sections:
        if s.id not in skip:
            by_cat[s.category or "other"].append(s)
    for items in by_cat.values():
        items.sort(key=lambda s: s.title.lower())
    ordered = [(c, by_cat[c]) for c in CATEGORY_ORDER if c in by_cat]
    extras = sorted(c for c in by_cat if c not in CATEGORY_ORDER)
    ordered += [(c, by_cat[c]) for c in extras]
    return ordered


def render_landing(
    sections: list[Section],
    out_path: str,
    base_href: str = "/",
    exclude_ids: list[str] | None = None,
) -> None:
    """Render the landing page from templates/landing.html.

    `exclude_ids` is a list of section ids to hide from the landing index.
    The corresponding HTML pages are still generated by render_sections()
    and remain reachable by URL; they're just omitted from the home page
    (and from the in-page nav / footer / quick links).
    """
    nav_groups = build_nav_groups(sections, exclude_ids)

    env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(_TEMPLATES_DIR)))
    tpl = env.get_template("landing.html")
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(
        tpl.render(
            nav_groups=nav_groups,
            cat_labels=CATEGORY_LABELS,
            cat_icons=CATEGORY_ICONS,
            base_href=base_href,
        ),
        encoding="utf-8",
    )
